import { RegionCode } from '@/types';

export const MAP_CONFIG = {
  width: 800,
  height: 400,

  projection: 'geoMercator' as const,
  projectionConfig: {
    scale: 147,
    center: [0, 20] as [number, number],
  },

  minZoom: 1,
  maxZoom: 8,
  zoomSensitivity: 0.5,

  defaultFill: '#D6D6DA',
  hoverFill: '#9CA3AF',
  selectedFill: '#6B7280',

  regionColors: {
    AS: '#3B82F6',
    AF: '#EF4444',
    EU: '#10B981',
    NA: '#F59E0B',
    SA: '#8B5CF6',
    OC: '#EC4899',
    ME: '#06B6D4',
  } as Record<RegionCode, string>,

  markerSize: {
    default: 8,
    hover: 12,
    selected: 14,
  },
  markerColor: '#DC2626',
  markerHoverColor: '#991B1B',
};

export const REGION_MAPPING: Record<string, RegionCode> = {
  // Asia
  Japan: 'AS',
  China: 'AS',
  'South Korea': 'AS',
  'North Korea': 'AS',
  Thailand: 'AS',
  Philippines: 'AS',
  India: 'AS',
  Vietnam: 'AS',
  Indonesia: 'AS',
  Malaysia: 'AS',
  Singapore: 'AS',
  Myanmar: 'AS',
  Burma: 'AS',
  Cambodia: 'AS',
  Laos: 'AS',
  Bangladesh: 'AS',
  Pakistan: 'AS',
  Afghanistan: 'AS',
  Nepal: 'AS',
  Bhutan: 'AS',
  'Sri Lanka': 'AS',
  Mongolia: 'AS',
  Kazakhstan: 'AS',
  Kyrgyzstan: 'AS',
  Tajikistan: 'AS',
  Turkmenistan: 'AS',
  Uzbekistan: 'AS',
  Taiwan: 'AS',
  'Hong Kong': 'AS',
  Macao: 'AS',
  'Timor-Leste': 'AS',
  'East Timor': 'AS',
  Brunei: 'AS',

  // Africa
  Kenya: 'AF',
  Tanzania: 'AF',
  Ethiopia: 'AF',
  'South Africa': 'AF',
  Nigeria: 'AF',
  Ghana: 'AF',
  Uganda: 'AF',
  Egypt: 'AF',
  Morocco: 'AF',
  Algeria: 'AF',
  Tunisia: 'AF',
  Libya: 'AF',
  Mauritania: 'AF',
  Sudan: 'AF',
  'South Sudan': 'AF',
  'S. Sudan': 'AF',
  Somalia: 'AF',
  Somaliland: 'AF',
  Mozambique: 'AF',
  Madagascar: 'AF',
  Cameroon: 'AF',
  'Ivory Coast': 'AF',
  "Côte d'Ivoire": 'AF',
  Niger: 'AF',
  Mali: 'AF',
  Senegal: 'AF',
  Zambia: 'AF',
  Zimbabwe: 'AF',
  Botswana: 'AF',
  Namibia: 'AF',
  Angola: 'AF',
  'Democratic Republic of the Congo': 'AF',
  'Dem. Rep. Congo': 'AF',
  'Republic of the Congo': 'AF',
  'Republic of Congo': 'AF',
  Congo: 'AF',
  'Congo-Brazzaville': 'AF',
  'Congo-Kinshasa': 'AF',
  Rwanda: 'AF',
  Burundi: 'AF',
  'Central African Republic': 'AF',
  'Central African Rep.': 'AF',
  Chad: 'AF',
  'W. Sahara': 'AF',
  'Western Sahara': 'AF',
  Eritrea: 'AF',
  Djibouti: 'AF',
  'Sierra Leone': 'AF',
  Liberia: 'AF',
  Togo: 'AF',
  Benin: 'AF',
  'Burkina Faso': 'AF',
  Guinea: 'AF',
  'Guinea-Bissau': 'AF',
  'Equatorial Guinea': 'AF',
  'Eq. Guinea': 'AF',
  Gabon: 'AF',
  'São Tomé and Príncipe': 'AF',
  'Sao Tome and Principe': 'AF',
  Comoros: 'AF',
  'Cape Verde': 'AF',
  Mayotte: 'AF',
  Réunion: 'AF',
  Reunion: 'AF',
  Malawi: 'AF',
  Lesotho: 'AF',
  Swaziland: 'AF',
  Eswatini: 'AF',
  Mauritius: 'AF',
  Seychelles: 'AF',

  // Europe
  France: 'EU',
  Germany: 'EU',
  Spain: 'EU',
  Italy: 'EU',
  Poland: 'EU',
  'United Kingdom': 'EU',
  UK: 'EU',
  Netherlands: 'EU',
  Belgium: 'EU',
  Switzerland: 'EU',
  Austria: 'EU',
  Portugal: 'EU',
  Greece: 'EU',
  Sweden: 'EU',
  Norway: 'EU',
  Denmark: 'EU',
  Finland: 'EU',
  Iceland: 'EU',
  Ireland: 'EU',
  Russia: 'EU',
  'Russian Federation': 'EU',
  Ukraine: 'EU',
  Romania: 'EU',
  'Czech Republic': 'EU',
  Czechia: 'EU',
  Hungary: 'EU',
  Belarus: 'EU',
  Bulgaria: 'EU',
  Serbia: 'EU',
  Croatia: 'EU',
  Slovakia: 'EU',
  Lithuania: 'EU',
  Latvia: 'EU',
  Estonia: 'EU',
  Slovenia: 'EU',
  'Bosnia and Herzegovina': 'EU',
  'Bosnia and Herz.': 'EU',
  'Bosnia & Herzegovina': 'EU',
  Albania: 'EU',
  Macedonia: 'EU',
  'North Macedonia': 'EU',
  Montenegro: 'EU',
  Kosovo: 'EU',
  Moldova: 'EU',
  Luxembourg: 'EU',
  Malta: 'EU',
  Cyprus: 'EU',
  Andorra: 'EU',
  Monaco: 'EU',
  Liechtenstein: 'EU',
  'San Marino': 'EU',
  'Vatican City': 'EU',

  // North America
  Mexico: 'NA',
  Canada: 'NA',
  Guatemala: 'NA',
  Honduras: 'NA',
  'United States': 'NA',
  'United States of America': 'NA',
  USA: 'NA',
  'Costa Rica': 'NA',
  Nicaragua: 'NA',
  Panama: 'NA',
  'El Salvador': 'NA',
  Belize: 'NA',
  Cuba: 'NA',
  Haiti: 'NA',
  'Dominican Republic': 'NA',
  'Dominican Rep.': 'NA',
  Jamaica: 'NA',
  'Trinidad and Tobago': 'NA',
  'Trinidad & Tobago': 'NA',
  'Puerto Rico': 'NA',
  Bahamas: 'NA',
  Barbados: 'NA',
  Greenland: 'NA',

  // South America
  Brazil: 'SA',
  Peru: 'SA',
  Colombia: 'SA',
  Argentina: 'SA',
  Ecuador: 'SA',
  Chile: 'SA',
  Venezuela: 'SA',
  Bolivia: 'SA',
  Paraguay: 'SA',
  Uruguay: 'SA',
  Guyana: 'SA',
  Suriname: 'SA',
  'French Guiana': 'SA',
  'Fr. Guiana': 'SA',
  'French Guyana': 'SA',
  Guyane: 'SA',
  'Falkland Islands': 'SA',
  'Falkland Is.': 'SA',

  // Oceania
  Australia: 'OC',
  'Papua New Guinea': 'OC',
  Fiji: 'OC',
  'New Zealand': 'OC',
  'Solomon Islands': 'OC',
  Vanuatu: 'OC',
  Samoa: 'OC',
  Tonga: 'OC',
  Micronesia: 'OC',
  Palau: 'OC',
  'Marshall Islands': 'OC',
  Kiribati: 'OC',
  Tuvalu: 'OC',
  Nauru: 'OC',
  'New Caledonia': 'OC',
  'French Polynesia': 'OC',

  // Middle East
  Jordan: 'ME',
  Lebanon: 'ME',
  UAE: 'ME',
  'United Arab Emirates': 'ME',
  Turkey: 'ME',
  Türkiye: 'ME',
  Israel: 'ME',
  Palestine: 'ME',
  'Saudi Arabia': 'ME',
  Iran: 'ME',
  Iraq: 'ME',
  Syria: 'ME',
  Yemen: 'ME',
  Oman: 'ME',
  Kuwait: 'ME',
  Qatar: 'ME',
  Bahrain: 'ME',
  Armenia: 'ME',
  Azerbaijan: 'ME',
  Georgia: 'ME',
};

export function getRegionFromCountry(country: string, coordinates?: [number, number]): RegionCode | null {
  // Special case: France in South America is French Guiana
  // Note: Current map (world-110m.json) doesn't include French Guiana as separate geometry
  if (country === 'France' && coordinates) {
    const [lon, lat] = coordinates;
    // French Guiana is roughly: lon -54 to -51, lat 2 to 6
    if (lon >= -54 && lon <= -51 && lat >= 2 && lat <= 6) {
      return 'SA';
    }
  }

  return REGION_MAPPING[country] || null;
}

export function getRegionCenter(regionCode: RegionCode): [number, number] {
  const centers: Record<RegionCode, [number, number]> = {
    AS: [100.6197, 34.0479],
    AF: [34.5085, -8.7832],
    EU: [15.2551, 54.526],
    NA: [-105.2551, 54.526],
    SA: [-55.4915, -8.7832],
    OC: [140.0188, -22.7359],
    ME: [42.551, 29.2985],
  };
  return centers[regionCode];
}
